name = "sleepingtigers"
compatibility_date = "2026-09-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "NEWSLETTERS"
id = "b15ed53d3d9c4bda94c16732a3e77ddf"

